<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>11ff492b-c01d-43e3-bed3-2a72907cf6e0</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Apps\CommandCenter.Web\CommandCenter.Web.csproj" />
    <ProjectReference Include="..\Apps\DemoControl.Web\DemoControl.Web.csproj" />
    <ProjectReference Include="..\Services\CommandCenter.Api\CommandCenter.Api.csproj" />
    <ProjectReference Include="..\Services\DemoScenario.Api\DemoScenario.Api.csproj" />
    <ProjectReference Include="..\Services\EnergyHub.Api\EnergyHub.Api.csproj" />
    <ProjectReference Include="..\Services\OperationsAgent.Api\OperationsAgent.Api.csproj" />
    <ProjectReference Include="..\Services\SecurityAgent.Api\SecurityAgent.Api.csproj" />
    <ProjectReference Include="..\Services\SecurityHub.Api\SecurityHub.Api.csproj" />
    <ProjectReference Include="..\Services\WorkforceAgent.Api\WorkforceAgent.Api.csproj" />
    <ProjectReference Include="..\Services\WorkforceHub.Api\WorkforceHub.Api.csproj" />
    <ProjectReference Include="..\Services\SmartPole.Simulator.Api\SmartPole.Simulator.Api.csproj" />
  </ItemGroup>

</Project>
